# Generated by Django 5.0.3 on 2025-10-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_matter_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
