# Generated by Django 5.0.3 on 2025-10-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_last_login_at_user_mfa_enforced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_pending_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
