# Generated by Django 5.0.3 on 2025-10-02 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_mfa_pending_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("codename", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["codename"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="accounts.permission"
            ),
        ),
    ]
