version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: legaltech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    build:
      context: ..
      dockerfile: devops/docker/minio.Dockerfile
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_URL: https://storage.legal.getbukd.com
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build:
      context: ..
      dockerfile: devops/docker/backend.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/legaltech
      S3_ENDPOINT_URL: https://storage.legal.getbukd.com
      S3_BUCKET_NAME: legaltech-dev
      DJANGO_SECRET_KEY: dev-secret
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,10.0.0.161,legal.getbukd.com,138.197.155.4
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://10.0.0.161:5173,https://legal.getbukd.com
      CSRF_TRUSTED_ORIGINS: http://localhost:5173,http://10.0.0.161:5173,https://legal.getbukd.com
      CA_REGION: ca-central-1
      STRIPE_SECRET_KEY: sk_test_stub
      STRIPE_WEBHOOK_SECRET: whsec_stub
      FRONTEND_BASE_URL: https://legal.getbukd.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-minio}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-minio123}
      S3_EXTERNAL_ENDPOINT_URL: https://storage.legal.getbukd.com
      FEATURE_CASE_TRACKER: "True"
      FEATURE_CONTRACT_ANALYSIS: "True"
      FEATURE_AI_RESEARCH: "True"
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: devops/docker/frontend.Dockerfile
    restart: unless-stopped
    volumes:
      - ../frontend:/app
    environment:
      VITE_API_BASE: https://legal.getbukd.com/api/v1
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
  minio-data:
