# Generated by Django 5.0.3 on 2025-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_564b1f_idx",
            old_name="notification_recipient_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_organiz_fb9709_idx",
            old_name="notification_org_type_idx",
        ),
    ]
