# Generated by Codex scaffold
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("tax_code", models.CharField(blank=True, max_length=32)),
                ("receipt_file", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="matters.matter"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="accounts.organization"),
                ),
            ],
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=32)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("sent", "Sent"), ("paid", "Paid"), ("overdue", "Overdue")], default="draft", max_length=16)),
                ("pdf_file", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="matters.matter"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="accounts.organization"),
                ),
            ],
            options={"ordering": ["-issue_date"], "unique_together": {("organization", "number")}},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("method", models.CharField(choices=[("stripe", "Stripe"), ("interac", "Interac e-Transfer"), ("manual", "Manual")], max_length=20)),
                ("external_ref", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.invoice"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="accounts.organization"),
                ),
            ],
            options={"ordering": ["-date"]},
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("minutes", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
                ("billable", models.BooleanField(default=True)),
                ("source", models.CharField(choices=[("email", "Email"), ("doc", "Document"), ("call", "Phone Call"), ("manual", "Manual")], default="manual", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_entries", to="matters.matter"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="time_entries", to="accounts.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="time_entries", to="accounts.user"),
                ),
            ],
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="TrustAccountBalance",
            fields=[
                (
                    "organization",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="accounts.organization"),
                ),
                ("balance_cents", models.BigIntegerField(default=0)),
            ],
            options={"verbose_name": "Trust Account Balance", "verbose_name_plural": "Trust Account Balances"},
        ),
    ]
