[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["B008"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
norecursedirs = ["node_modules", "frontend"]
python_files = ["test_*.py"]

[tool.coverage.run]
branch = true
source = ["accounts", "matters", "billing", "portal", "services", "core", "integrations"]
omit = ["*/migrations/*"]

[tool.mypy]
python_version = "3.11"
plugins = []
django_settings_module = "core.settings"
ignore_missing_imports = true
