# Generated by Django 5.0.3 on 2025-10-01 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_mfa_pending_secret"),
        ("matters", "0004_rename_matters_mat_reference_287ad0_idx_matters_mat_referen_0e5285_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDeadline",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deadline_type", models.CharField(max_length=120)),
                ("due_date", models.DateTimeField()),
                ("rule_reference", models.CharField(blank=True, max_length=120)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notifications_sent", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.AddField(
            model_name="casedeadline",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_deadlines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casedeadline",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deadlines",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="casedeadline",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_deadlines",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="casedeadline",
            index=models.Index(
                fields=["organization", "due_date"], name="matters_cas_organiz_bb078b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedeadline",
            index=models.Index(
                fields=["organization", "status"], name="matters_cas_organiz_b316ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedeadline",
            index=models.Index(
                fields=["matter", "due_date"], name="matters_cas_matter__41c41d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedeadline",
            index=models.Index(
                fields=["due_date", "status"], name="matters_cas_due_dat_7156e0_idx"
            ),
        ),
    ]
