# Generated by Django 5.0.3 on 2025-10-02 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_permission_role_is_custom_alter_role_name_and_more"),
        ("matters", "0005_casedeadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatterAccess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lawyer", "Lawyer"),
                            ("paralegal", "Paralegal"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=24,
                    ),
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name="matter",
            new_name="matters_mat_referen_0e5285_idx",
            old_name="matters_mat_reference_287ad0_idx",
        ),
        migrations.AddField(
            model_name="matteraccess",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_list",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="matteraccess",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matter_access",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="matteraccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matter_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matter",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="matters",
                through="matters.MatterAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="matteraccess",
            index=models.Index(
                fields=["organization", "user"], name="matters_mat_organiz_aef9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matteraccess",
            index=models.Index(
                fields=["organization", "matter"], name="matters_mat_organiz_1149d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matteraccess",
            unique_together={("matter", "user")},
        ),
    ]
