# Generated by Codex scaffold
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("actor_type", models.CharField(choices=[("user", "User"), ("client", "Client"), ("system", "System")], max_length=20)),
                ("action", models.CharField(max_length=120)),
                ("resource_type", models.CharField(max_length=120)),
                ("resource_id", models.CharField(max_length=120)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="accounts.organization"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["organization", "created_at"], name="audit_event_org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["organization", "resource_type"], name="audit_event_org_resource_idx"),
        ),
    ]
