# Generated by Django 5.0.3 on 2025-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_organiz_4fc53a_idx",
            old_name="audit_event_org_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="audit_audit_organiz_e67825_idx",
            old_name="audit_event_org_resource_idx",
        ),
    ]
