# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Format check with Black
      run: |
        black --check .
    
    - name: Lint with Ruff
      run: |
        ruff check .
    
    - name: Type check with MyPy
      run: |
        mypy .
      continue-on-error: true  # Don't fail build on type errors yet
    
    - name: Test with pytest
      run: |
        pytest tests/ --verbose
      continue-on-error: true  # Don't fail until DB is set up

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint with ESLint
      run: npm run lint
      continue-on-error: true  # Don't fail until all issues are fixed
    
    - name: Type check with TypeScript
      run: npm run typecheck
      continue-on-error: true  # Don't fail until all issues are fixed
    
    - name: Test with Vitest
      run: npm run test -- --run
